### ISSUE TITLE
测试发现处理冲突时会发生死循环问题

### ISSUE THREAD

**Issue by XingheYao** [slow-steppers/NeighborHash#1]
在map中emplace数据时，prev_slot的offset读取到是0，导致陷入死循环
https://github.com/slow-steppers/NeighborHash/blob/main/neighbor_hash/neighbor_hash.h#L1222

**Comment by ZT-Alonzo** [comment]
麻烦您提供一下最小复现集

**Comment by XingheYao** [comment]
定位到了，是因为这个地方erase的时候会把offset清空，导致冲突的链断掉了，https://github.com/slow-steppers/NeighborHash/blob/main/neighbor_hash/neighbor_hash.h#L1107

**Comment by wudisheng** [comment]
十分感谢您对该问题的调查和定位，我们目前可以初步确定此处存在问题，会尽快完成修复。

顺便问一下，您是在测试代码中穿插调用 `erase()` 方法了么？因为 `EraseSlot()` 并不在 `emplace()` 的调用路径中。

**Comment by XingheYao** [comment]
是的

**Comment by ZT-Alonzo** [comment]
这个版本发出来的时候并没有仔细测试erase的场景，感谢您定位修复

**Comment by 396848385** [comment]
删除时候能否返回下一个迭代器 写了一版 帮忙看看 @XingheYao @wudisheng @ZT-Alonzo

**Comment by 396848385** [comment]
这个erase除了这里还有一个bug 就是如果要删的key是kUnOccupiedKey 那么会直接SetUnOccupiedKey() 这个函数会把kUnOccupiedKey对应的slot的offset设置为0  直接把冲突链断掉 这样的话所有和kUnOccupiedKey的slot_index一样的值都无法在erase的时候被找到了

**Comment by wudisheng** [comment]
> 删除时候能否返回下一个迭代器 写了一版 帮忙看看 @XingheYao @wudisheng @ZT-Alonzo

您提交PR了嘛，我这里貌似没有看到。

另外，抱歉我们最近能投入这个项目上的时间很有限，查看和回复都会比较慢。

**Comment by wudisheng** [comment]
> 这个erase除了这里还有一个bug 就是如果要删的key是kUnOccupiedKey 那么会直接SetUnOccupiedKey() 这个函数会把kUnOccupiedKey对应的slot的offset设置为0 直接把冲突链断掉 这样的话所有和kUnOccupiedKey的slot_index一样的值都无法在erase的时候被找到了

@ZT-Alonzo 这里要不你重新考虑/设计一下？其实我们的典型使用场景里根本就没有erase，要不就把immutable那一套拿过来揉一揉然后分化出来一个版本吧…
