### ISSUE TITLE
SIMD_FIND

### ISSUE THREAD

**Issue by lyjps** [slow-steppers/NeighborHash#10]
<img width="925" alt="截屏2024-10-24 17 27 27" src="https://github.com/user-attachments/assets/e07ab5cc-728d-4115-bcb0-286984fdcc98">
每次消费kSIMDWidth个元素，包括本次命中的元素和之前命中的元素个数之和。
这里是如何保证之前取出的之前命中的元素是有效的呢，如果是无效的空置，这里的consume_cnt的计算是不是存在问题呢？

**Comment by ZT-Alonzo** [comment]
每次比较的kSIMDWidth个元素一定是有效的，不会有"无效的空置"。可以仔细看看后面的refill相关逻辑。
