### ISSUE TITLE
erase时候针对kUnOccupiedKey删除时的bug

### ISSUE THREAD

**Issue by 396848385** [slow-steppers/NeighborHash#8]
目前源码是有bug的 在`erased_key == kUnOccupiedKey`的时候 不能直接调用`SetUnOccupiedKey` 因为会把kUnOccupiedKey所在slot的offset设置为0 通过emplace的实现可以明确kUnOccupiedKey总是在冲突链的第一位， 这样所有和kUnOccupiedKey的slot_index一致的冲突链中的其他值就都找不到了
![image](https://github.com/user-attachments/assets/e316391b-ccd6-4739-861c-ca70e7ddf9dd)
![image](https://github.com/user-attachments/assets/f1104b73-a34e-417e-873b-f3586574dfc7)

**Comment by ZT-Alonzo** [comment]
看起来删除的时候不应该reset这个slot的offset

**Comment by 396848385** [comment]
是的  另外放便帮忙看下earse方法返回迭代器的实现么 我在前一个issue中也发了截图
